### ISSUE TITLE
Can't see the players in SplitScreen demo

### ISSUE THREAD

**Issue by NQNStudios** [HaxeFlixel/flixel-demos#281]
First of all, the SplitScreen demo won't play in browsers anymore because it's hosted as a Flash game: https://haxeflixel.com/demos/SplitScreen/

In my clone of the repository, I ran with `lime test html5` and it runs without any errors to console, but I can't see the players (which judging from the code should just be solid-color squares).

**Comment by Geokureli** [comment]
the problem is that the tilemap doesn't show because of how they are loading the tile asset. the players aren't showing because they are falling below the camera too fast. the same thing happens on [EZPlatformer](https://haxeflixel.com/demos/EZPlatformer/) but it's easier to  spot.

Side note, on EZPlatformer it seems that the tilemap doesn't load on the first try, but succeeds on the second attempt that happens when the player triggers a reset to playstate. This is because they load the tilemap asset using `FlxGraphic.fromClass(GraphicAuto)`. On web, it seems the image is loaded asynchronously and seen as a 0x0 image when creating the tilemap.

we should add the autotile assets to the [include.xml#L17](https://github.com/HaxeFlixel/flixel/blob/dev/include.xml#L17) asset list and load them via `"flixel/images/tile/autotiles.png"`

**Comment by Geokureli** [comment]
@Gama11 I was expecting the html5 preview of [splitscreen demo](https://haxeflixel.com/demos/SplitScreen/) to show up, now. Is it manually disabled somewhere? I see [the EZPlatformer demo](https://haxeflixel.com/demos/EZPlatformer/) is fixed from #2402

**Comment by Gama11** [comment]
Possibly, in the haxeflixel.com repo.
