### ISSUE TITLE
BSPMapGen maps are aliased on HTML5

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/flixel-demos#300]
I'm not sure if there's something wrong with html bitmap drawing, or if the original coder specifically used a method that was very flash specific

Flash:
<img width="635" alt="Screen Shot 2022-05-14 at 11 49 24 AM" src="https://user-images.githubusercontent.com/2609513/168441193-226cd4e3-cc0e-4996-8236-e99af090bf7a.png">
Html:
<img width="634" alt="Screen Shot 2022-05-14 at 11 49 43 AM" src="https://user-images.githubusercontent.com/2609513/168441194-8dcc5fcc-7f0c-4be7-bba3-e2e78f9ec86f.png">
Mac:
<img width="635" alt="Screen Shot 2022-05-14 at 12 11 58 PM" src="https://user-images.githubusercontent.com/2609513/168441880-4ab276f3-433e-4165-95a7-267c37daa790.png">

**Comment by UncertainProd** [comment]
It looks like this is related to [this issue with html5 canvases automatically antialiasing pixels that are on non-integer coordinates](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas#avoid_floating-point_coordinates_and_use_integers_instead). And since openfl uses CanvasRenderer to draw stuff to bitmapdata objects, it gets affected by this as well. I think this can be fixed by just rounding off the rectangles' coordinates to the nearest integer.
