### ISSUE TITLE
add fullscreen button to all demo pages

### ISSUE THREAD

**Issue by Geokureli** [HaxeFlixel/flixel-demos#322]
most of these are unplayable on mobile without it

**Comment by ninjamuffin99** [comment]
the way I think I'll go about this is what I'll call the "itch.io" method (since it seems like that's what itch does!)

Which is to have a button on the site that is added to each demo page that fullscreens the iframe.

1. enable the demos to be resized (see PR #336 )
2. adding button to resize the iframe on the haxeflixel.com side (see PR https://github.com/HaxeFlixel/haxeflixel.com/pull/259)

**Comment by ninjamuffin99** [comment]
this should be live at: https://dev.haxeflixel.com/demos/

**Comment by ninjamuffin99** [comment]
This is live and merged, so I will close this issue :)
